### ISSUE TITLE
neo4j的数据库无法导入

### ISSUE THREAD

**Issue by wwwjljj** [Pelhans/Z_knowledge_graph#7]
neo4j 版本4.1
数据库下载的是百度网盘中百度对应的neo4j 文件，加压缩为graph.db目录
把目录复制到neo4j对应的data/database/下，修改配置文件的默认数据库名字为graph.db，重新启动neo4j服服务
登录后提示数据库不可用，报错位置的store version，新手，不太熟悉，具体如下：

2020-08-13 13:02:42.154+0000 ERROR [o.n.d.d.DefaultDatabaseManager] Failed to start database: graph.db An error occurred! Unable to start database with name `graph.db`.
org.neo4j.dbms.api.DatabaseManagementException: An error occurred! Unable to start database with name `graph.db`.
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:191)
	at org.neo4j.dbms.database.DefaultDatabaseManager.startDatabase(DefaultDatabaseManager.java:132)
	at org.neo4j.dbms.database.DefaultDatabaseManager.initialiseDefaultDatabase(DefaultDatabaseManager.java:64)
	at org.neo4j.dbms.database.DefaultDatabaseInitializer.start0(DefaultDatabaseInitializer.java:39)
	at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:124)
	at org.neo4j.kernel.lifecycle.SafeLifecycle.start(SafeLifecycle.java:138)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown store version 'v0.A.8'
	at org.neo4j.kernel.database.Database.start(Database.java:497)
	at org.neo4j.dbms.database.AbstractDatabaseManager.startDatabase(AbstractDatabaseManager.java:187)
	... 13 more
Caused by: java.lang.IllegalArgumentException: Unknown store version 'v0.A.8'
	at org.neo4j.kernel.impl.store.format.RecordFormatSelector.selectForVersion(RecordFormatSelector.java:106)
	at org.neo4j.kernel.impl.storemigration.RecordStoreVersionCheck.versionInformation(RecordStoreVersionCheck.java:92)
	at org.neo4j.kernel.impl.storemigration.StoreUpgrader.migrateIfNeeded(StoreUpgrader.java:160)
	at org.neo4j.kernel.impl.storemigration.DatabaseMigrator.migrate(DatabaseMigrator.java:107)
	at org.neo4j.kernel.database.Database.upgradeStore(Database.java:533)
	at org.neo4j.kernel.database.Database.start(Database.java:360)
	... 14 more
2020-08-13 13:02:42.19

**Comment by wwwjljj** [comment]
换到neo4j 3.5.7 版本，打开配置upgrade后，可以使用了
![image](https://user-images.githubusercontent.com/1861277/90225333-c0f9e880-de43-11ea-8a25-cc37948a0078.png)
